# Generated by Django 4.2.3 on 2023-07-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_test', '0002_dogcatmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDogCatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('text', models.CharField(max_length=25)),
                ('dog', models.BooleanField(default=False)),
                ('cat', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='DogCatModel',
        ),
        migrations.DeleteModel(
            name='PostModel',
        ),
    ]
