# Generated by Django 4.2.3 on 2023-07-30 22:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form_test', '0003_postdogcatmodel_delete_dogcatmodel_delete_postmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdogcatmodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
